### ISSUE TITLE
Not Enough Tags

### ISSUE THREAD

**Issue by Triagle** [PopeLevi/makedocker#1]
One complaint I've received from our clients of late is an inability to find this project. In order to increase corporate-client synergy and double plus our win win situation I recommend a hard and fast strategy to increase the number of tags on this project. Marketing has brainstormed some excellent terms all of which I think you should include:

- Web 4.0
- Responsive
- Bean
- Agile
- Electron
- Chrome
- Bezel-less
- Augmented Reality Solution
- Virtual Reality Hackspace
- Functional
- Reaction
- Blockchain
- Mesh Network
- Transhuman
- Adaptive Security Architecture
- Mobile first
- Webpack
- Gulp
- Yarn
- node.js
- PEP-8 compliant
- Drones
- Virtual Personal Assistant
- Decentralized
- Smart Home Hub
- Smart Appliance

In any case we can double back on the ideation process in our next standard and task poker our way out onto a stable burndown.

Off to play golf,

Roger (Corporate Marketing Consulting Strategist)

**Comment by PopeLevi** [comment]
Hello Roger

I'm a bit tied up with work and such, so I don't have much time for this project at present.
If you would like to submit a pull request implementing your changes, that'd be great. Otherwise, I can make the changes, but that'll be during my annual leave (~2 weeks from now)

Cheers

**Comment by PopeLevi** [comment]
Hello Roger

I've added nine more tags to the project page. GitHub won't allow me to add more than twenty topics, so I suppose this will have to do for now.

In my opinion a maximum of twenty topics seems to be a strange, arbitrary restriction. Perhaps this is a bug on GitHub's end?

Cheers
